/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DbtestRouteImport } from './routes/dbtest'
import { Route as AdmindevRouteImport } from './routes/admindev'
import { Route as IndexRouteImport } from './routes/index'

const DbtestRoute = DbtestRouteImport.update({
  id: '/dbtest',
  path: '/dbtest',
  getParentRoute: () => rootRouteImport,
} as any)
const AdmindevRoute = AdmindevRouteImport.update({
  id: '/admindev',
  path: '/admindev',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admindev': typeof AdmindevRoute
  '/dbtest': typeof DbtestRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admindev': typeof AdmindevRoute
  '/dbtest': typeof DbtestRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admindev': typeof AdmindevRoute
  '/dbtest': typeof DbtestRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/admindev' | '/dbtest'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/admindev' | '/dbtest'
  id: '__root__' | '/' | '/admindev' | '/dbtest'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdmindevRoute: typeof AdmindevRoute
  DbtestRoute: typeof DbtestRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/dbtest': {
      id: '/dbtest'
      path: '/dbtest'
      fullPath: '/dbtest'
      preLoaderRoute: typeof DbtestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admindev': {
      id: '/admindev'
      path: '/admindev'
      fullPath: '/admindev'
      preLoaderRoute: typeof AdmindevRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdmindevRoute: AdmindevRoute,
  DbtestRoute: DbtestRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
